import type { Metadata } from 'next';
import './globals.css';
import NavbarComponent from '@/components/navbar/NavbarComponent';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='sv'>
      <body>
        <NavbarComponent />
        {children}
      </body>
    </html>
  );
}
